Repository bemerkenswert/carbotracker, pull requests merged in 2024-05, with the labels that each got.

#25 Fix Login Bug
  apps/carbotracker/src/main.ts
Labels: merge please

#45 fix dependency
  package-lock.json
  package.json
Labels: dependencies, merge please

#31 create automatic emulator setup
  apps/carbotracker/firebase-data/development/auth_export/accounts.json
  apps/carbotracker/firebase-data/development/auth_export/config.json
  apps/carbotracker/firebase-data/development/firebase-export-metadata.json
  apps/carbotracker/firebase-data/development/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  apps/carbotracker/firebase-data/development/firestore_export/all_namespaces/all_kinds/output-0
  apps/carbotracker/firebase-data/development/firestore_export/firestore_export.overall_export_metadata
  apps/carbotracker/project.json
  apps/carbotracker/src/app/app.config.ts
  apps/carbotracker/src/environments/environment.development.ts
  apps/carbotracker/src/environments/environment.ts
Labels: merge please, DX

#44 Show snack bar and navigate back to product list after saving product
  apps/carbotracker/src/products-feature/+state/actions/api.actions.ts
  apps/carbotracker/src/products-feature/+state/actions/component.actions.ts
  apps/carbotracker/src/products-feature/+state/actions/routing.actions.ts
  apps/carbotracker/src/products-feature/+state/actions/snackbar.actions.ts
  apps/carbotracker/src/products-feature/+state/effects/api.effects.ts
  apps/carbotracker/src/products-feature/+state/effects/routing.effects.ts
  apps/carbotracker/src/products-feature/+state/effects/snackbar.effects.ts
  apps/carbotracker/src/products-feature/+state/products.reducer.ts
  apps/carbotracker/src/products-feature/pages/CreateProductPage/create-product-page.component.ts
  apps/carbotracker/src/products-feature/pages/EditProductPage/edit-product-page.component.ts
  apps/carbotracker/src/products-feature/pages/ProductsPage/products-page.component.ts
  apps/carbotracker/src/products-feature/products.routes.ts
  apps/carbotracker/src/products-feature/services/products.service.ts
Labels: merge please
